-- Insert decks
INSERT INTO decks (title_es, title_ru, description, level, topic, icon) VALUES
('Comida y Bebidas', 'Еда и Напитки', 'Основные слова о еде и напитках', 'A1', 'food', '🍕'),
('Viajes y Transporte', 'Путешествия и Транспорт', 'Слова для путешествий', 'A1', 'travel', '✈️'),
('Vida Cotidiana', 'Повседневная Жизнь', 'Слова для дома и быта', 'A1', 'daily', '🏠'),
('Verbos Comunes', 'Общие Глаголы', 'Самые частые глаголы', 'A1', 'verbs', '🎯'),
('Adjetivos Comunes', 'Общие Прилагательные', 'Описание людей и вещей', 'A1', 'adjectives', '⭐');

-- Deck 1: Food & Drinks (100 words)
INSERT INTO cards (deck_id, spanish, russian, part_of_speech, example_es, example_ru, difficulty) 
SELECT 
  (SELECT id FROM decks WHERE topic = 'food'),
  spanish, russian, part_of_speech, example_es, example_ru, difficulty
FROM (VALUES
  ('agua', 'вода', 'noun', 'Quiero un vaso de agua', 'Я хочу стакан воды', 1),
  ('pan', 'хлеб', 'noun', 'El pan está fresco', 'Хлеб свежий', 1),
  ('leche', 'молоко', 'noun', 'Tomo leche en el desayuno', 'Я пью молоко на завтрак', 1),
  ('café', 'кофе', 'noun', 'Me gusta el café negro', 'Мне нравится чёрный кофе', 1),
  ('té', 'чай', 'noun', 'Prefiero té verde', 'Я предпочитаю зелёный чай', 1),
  ('vino', 'вино', 'noun', 'Una copa de vino tinto', 'Бокал красного вина', 2),
  ('cerveza', 'пиво', 'noun', 'Una cerveza fría', 'Холодное пиво', 1),
  ('jugo', 'сок', 'noun', 'Jugo de naranja natural', 'Натуральный апельсиновый сок', 1),
  ('carne', 'мясо', 'noun', 'La carne está bien cocida', 'Мясо хорошо приготовлено', 2),
  ('pollo', 'курица', 'noun', 'Pollo asado con papas', 'Жареная курица с картошкой', 1),
  ('pescado', 'рыба', 'noun', 'Pescado fresco del mar', 'Свежая морская рыба', 2),
  ('arroz', 'рис', 'noun', 'Arroz blanco hervido', 'Варёный белый рис', 1),
  ('pasta', 'паста', 'noun', 'Pasta con salsa de tomate', 'Паста с томатным соусом', 1),
  ('ensalada', 'салат', 'noun', 'Ensalada verde fresca', 'Свежий зелёный салат', 1),
  ('sopa', 'суп', 'noun', 'Sopa de verduras caliente', 'Горячий овощной суп', 1),
  ('queso', 'сыр', 'noun', 'Queso manchego español', 'Испанский сыр манчего', 2),
  ('huevo', 'яйцо', 'noun', 'Huevos revueltos', 'Яичница-болтунья', 1),
  ('mantequilla', 'масло', 'noun', 'Pan con mantequilla', 'Хлеб с маслом', 2),
  ('azúcar', 'сахар', 'noun', 'Café con azúcar', 'Кофе с сахаром', 1),
  ('sal', 'соль', 'noun', 'Un poco de sal', 'Немного соли', 1),
  ('pimienta', 'перец', 'noun', 'Sal y pimienta', 'Соль и перец', 2),
  ('aceite', 'масло (растительное)', 'noun', 'Aceite de oliva', 'Оливковое масло', 2),
  ('vinagre', 'уксус', 'noun', 'Vinagre balsámico', 'Бальзамический уксус', 3),
  ('tomate', 'помидор', 'noun', 'Tomates rojos maduros', 'Спелые красные помидоры', 1),
  ('cebolla', 'лук', 'noun', 'Cebolla picada', 'Нарезанный лук', 2),
  ('ajo', 'чеснок', 'noun', 'Diente de ajo', 'Зубчик чеснока', 2),
  ('patata', 'картофель', 'noun', 'Patatas fritas', 'Жареная картошка', 1),
  ('zanahoria', 'морковь', 'noun', 'Zanahorias crudas', 'Сырая морковь', 2),
  ('lechuga', 'салат (листовой)', 'noun', 'Hojas de lechuga', 'Листья салата', 2),
  ('pepino', 'огурец', 'noun', 'Pepino fresco', 'Свежий огурец', 2),
  ('manzana', 'яблоко', 'noun', 'Manzana roja dulce', 'Сладкое красное яблоко', 1),
  ('naranja', 'апельсин', 'noun', 'Naranja jugosa', 'Сочный апельсин', 1),
  ('plátano', 'банан', 'noun', 'Plátano maduro', 'Спелый банан', 1),
  ('fresa', 'клубника', 'noun', 'Fresas con crema', 'Клубника со сливками', 2),
  ('uva', 'виноград', 'noun', 'Racimo de uvas', 'Гроздь винограда', 2),
  ('limón', 'лимон', 'noun', 'Jugo de limón', 'Лимонный сок', 1),
  ('pera', 'груша', 'noun', 'Pera madura', 'Спелая груша', 2),
  ('sandía', 'арбуз', 'noun', 'Sandía fresca', 'Свежий арбуз', 2),
  ('melón', 'дыня', 'noun', 'Melón dulce', 'Сладкая дыня', 2),
  ('piña', 'ананас', 'noun', 'Piña tropical', 'Тропический ананас', 2),
  ('chocolate', 'шоколад', 'noun', 'Chocolate negro', 'Тёмный шоколад', 1),
  ('helado', 'мороженое', 'noun', 'Helado de vainilla', 'Ванильное мороженое', 1),
  ('pastel', 'торт', 'noun', 'Pastel de cumpleaños', 'Торт на день рождения', 2),
  ('galleta', 'печенье', 'noun', 'Galletas de chocolate', 'Шоколадное печенье', 1),
  ('dulce', 'конфета', 'noun', 'Dulces de colores', 'Разноцветные конфеты', 1),
  ('miel', 'мёд', 'noun', 'Miel de abeja', 'Пчелиный мёд', 2),
  ('mermelada', 'варенье', 'noun', 'Mermelada de fresa', 'Клубничное варенье', 2),
  ('yogur', 'йогурт', 'noun', 'Yogur natural', 'Натуральный йогурт', 1),
  ('jamón', 'ветчина', 'noun', 'Jamón serrano', 'Хамон серрано', 2),
  ('salchicha', 'колбаса', 'noun', 'Salchichas alemanas', 'Немецкие колбаски', 2),
  ('hamburguesa', 'гамбургер', 'noun', 'Hamburguesa con queso', 'Гамбургер с сыром', 1),
  ('pizza', 'пицца', 'noun', 'Pizza margarita', 'Пицца маргарита', 1),
  ('bocadillo', 'бутерброд', 'noun', 'Bocadillo de jamón', 'Бутерброд с ветчиной', 1),
  ('tostada', 'тост', 'noun', 'Tostada con mantequilla', 'Тост с маслом', 1),
  ('cereal', 'хлопья', 'noun', 'Cereales con leche', 'Хлопья с молоком', 1),
  ('desayuno', 'завтрак', 'noun', 'Desayuno completo', 'Полный завтрак', 1),
  ('almuerzo', 'обед', 'noun', 'Hora del almuerzo', 'Время обеда', 1),
  ('cena', 'ужин', 'noun', 'Cena ligera', 'Лёгкий ужин', 1),
  ('comida', 'еда', 'noun', 'Comida casera', 'Домашняя еда', 1),
  ('bebida', 'напиток', 'noun', 'Bebida fría', 'Холодный напиток', 1),
  ('menú', 'меню', 'noun', 'El menú del día', 'Меню дня', 1),
  ('plato', 'блюдо', 'noun', 'Plato principal', 'Основное блюдо', 1),
  ('taza', 'чашка', 'noun', 'Una taza de café', 'Чашка кофе', 1),
  ('vaso', 'стакан', 'noun', 'Un vaso de agua', 'Стакан воды', 1),
  ('botella', 'бутылка', 'noun', 'Botella de vino', 'Бутылка вина', 1),
  ('cuchara', 'ложка', 'noun', 'Cuchara de sopa', 'Суповая ложка', 1),
  ('tenedor', 'вилка', 'noun', 'Tenedor y cuchillo', 'Вилка и нож', 1),
  ('cuchillo', 'нож', 'noun', 'Cuchillo afilado', 'Острый нож', 1),
  ('servilleta', 'салфетка', 'noun', 'Servilleta de papel', 'Бумажная салфетка', 2),
  ('mesa', 'стол', 'noun', 'Mesa del comedor', 'Обеденный стол', 1),
  ('silla', 'стул', 'noun', 'Silla cómoda', 'Удобный стул', 1),
  ('restaurante', 'ресторан', 'noun', 'Restaurante italiano', 'Итальянский ресторан', 1),
  ('bar', 'бар', 'noun', 'Bar de tapas', 'Бар с тапас', 1),
  ('cafetería', 'кафе', 'noun', 'Cafetería acogedora', 'Уютное кафе', 1),
  ('cocina', 'кухня', 'noun', 'Cocina moderna', 'Современная кухня', 1),
  ('nevera', 'холодильник', 'noun', 'Comida en la nevera', 'Еда в холодильнике', 2),
  ('horno', 'духовка', 'noun', 'Hornear en el horno', 'Запекать в духовке', 2),
  ('microondas', 'микроволновка', 'noun', 'Calentar en el microondas', 'Разогреть в микроволновке', 2),
  ('estufa', 'плита', 'noun', 'Cocinar en la estufa', 'Готовить на плите', 2),
  ('receta', 'рецепт', 'noun', 'Receta tradicional', 'Традиционный рецепт', 2),
  ('ingrediente', 'ингредиент', 'noun', 'Ingredientes frescos', 'Свежие ингредиенты', 2),
  ('sabor', 'вкус', 'noun', 'Sabor delicioso', 'Восхитительный вкус', 2),
  ('dulce', 'сладкий', 'adjective', 'Postre muy dulce', 'Очень сладкий десерт', 1),
  ('salado', 'солёный', 'adjective', 'Demasiado salado', 'Слишком солёный', 1),
  ('amargo', 'горький', 'adjective', 'Café amargo', 'Горький кофе', 2),
  ('ácido', 'кислый', 'adjective', 'Limón ácido', 'Кислый лимон', 2),
  ('picante', 'острый', 'adjective', 'Salsa picante', 'Острый соус', 2),
  ('fresco', 'свежий', 'adjective', 'Pan fresco', 'Свежий хлеб', 1),
  ('caliente', 'горячий', 'adjective', 'Sopa caliente', 'Горячий суп', 1),
  ('frío', 'холодный', 'adjective', 'Bebida fría', 'Холодный напиток', 1),
  ('delicioso', 'вкусный', 'adjective', 'Comida deliciosa', 'Вкусная еда', 1),
  ('rico', 'вкусный', 'adjective', 'Muy rico', 'Очень вкусно', 1),
  ('comer', 'есть', 'verb', 'Voy a comer', 'Я буду есть', 1),
  ('beber', 'пить', 'verb', 'Quiero beber agua', 'Я хочу пить воду', 1),
  ('cocinar', 'готовить', 'verb', 'Me gusta cocinar', 'Мне нравится готовить', 1),
  ('probar', 'пробовать', 'verb', 'Quiero probar esto', 'Я хочу попробовать это', 2),
  ('pedir', 'заказывать', 'verb', 'Voy a pedir pizza', 'Я закажу пиццу', 2),
  ('servir', 'подавать', 'verb', 'Servir la comida', 'Подавать еду', 2),
  ('preparar', 'готовить', 'verb', 'Preparar el desayuno', 'Готовить завтрак', 2),
  ('cortar', 'резать', 'verb', 'Cortar el pan', 'Резать хлеб', 1),
  ('mezclar', 'смешивать', 'verb', 'Mezclar los ingredientes', 'Смешивать ингредиенты', 2),
  ('hervir', 'кипятить', 'verb', 'Hervir el agua', 'Кипятить воду', 2)
) AS t(spanish, russian, part_of_speech, example_es, example_ru, difficulty);

-- Deck 2: Travel & Transport (100 words)
INSERT INTO cards (deck_id, spanish, russian, part_of_speech, example_es, example_ru, difficulty) 
SELECT 
  (SELECT id FROM decks WHERE topic = 'travel'),
  spanish, russian, part_of_speech, example_es, example_ru, difficulty
FROM (VALUES
  ('avión', 'самолёт', 'noun', 'Viajar en avión', 'Путешествовать на самолёте', 1),
  ('tren', 'поезд', 'noun', 'Tomar el tren', 'Сесть на поезд', 1),
  ('autobús', 'автобус', 'noun', 'Parada de autobús', 'Автобусная остановка', 1),
  ('coche', 'машина', 'noun', 'Alquilar un coche', 'Арендовать машину', 1),
  ('taxi', 'такси', 'noun', 'Llamar un taxi', 'Вызвать такси', 1),
  ('metro', 'метро', 'noun', 'Estación de metro', 'Станция метро', 1),
  ('bicicleta', 'велосипед', 'noun', 'Montar en bicicleta', 'Ездить на велосипеде', 1),
  ('barco', 'корабль', 'noun', 'Viajar en barco', 'Путешествовать на корабле', 2),
  ('aeropuerto', 'аэропорт', 'noun', 'Ir al aeropuerto', 'Ехать в аэропорт', 1),
  ('estación', 'вокзал', 'noun', 'Estación de tren', 'Железнодорожный вокзал', 1),
  ('billete', 'билет', 'noun', 'Comprar un billete', 'Купить билет', 1),
  ('pasaporte', 'паспорт', 'noun', 'Mostrar el pasaporte', 'Показать паспорт', 1),
  ('maleta', 'чемодан', 'noun', 'Hacer la maleta', 'Собирать чемодан', 1),
  ('equipaje', 'багаж', 'noun', 'Facturar el equipaje', 'Сдать багаж', 2),
  ('mochila', 'рюкзак', 'noun', 'Llevar una mochila', 'Нести рюкзак', 1),
  ('hotel', 'отель', 'noun', 'Reservar un hotel', 'Забронировать отель', 1),
  ('habitación', 'номер', 'noun', 'Habitación doble', 'Двухместный номер', 1),
  ('reserva', 'бронирование', 'noun', 'Hacer una reserva', 'Сделать бронирование', 2),
  ('recepción', 'ресепшн', 'noun', 'Ir a la recepción', 'Идти на ресепшн', 2),
  ('llave', 'ключ', 'noun', 'Llave de la habitación', 'Ключ от номера', 1),
  ('mapa', 'карта', 'noun', 'Mirar el mapa', 'Смотреть на карту', 1),
  ('guía', 'гид', 'noun', 'Guía turístico', 'Туристический гид', 2),
  ('turista', 'турист', 'noun', 'Muchos turistas', 'Много туристов', 1),
  ('viaje', 'путешествие', 'noun', 'Buen viaje', 'Счастливого пути', 1),
  ('vacaciones', 'отпуск', 'noun', 'Ir de vacaciones', 'Ехать в отпуск', 1),
  ('playa', 'пляж', 'noun', 'Día en la playa', 'День на пляже', 1),
  ('montaña', 'гора', 'noun', 'Subir la montaña', 'Подниматься на гору', 1),
  ('ciudad', 'город', 'noun', 'Ciudad grande', 'Большой город', 1),
  ('pueblo', 'деревня', 'noun', 'Pueblo pequeño', 'Маленькая деревня', 1),
  ('país', 'страна', 'noun', 'Visitar un país', 'Посетить страну', 1),
  ('calle', 'улица', 'noun', 'Caminar por la calle', 'Идти по улице', 1),
  ('avenida', 'проспект', 'noun', 'Avenida principal', 'Главный проспект', 2),
  ('plaza', 'площадь', 'noun', 'Plaza mayor', 'Главная площадь', 1),
  ('puente', 'мост', 'noun', 'Cruzar el puente', 'Пересечь мост', 2),
  ('museo', 'музей', 'noun', 'Visitar el museo', 'Посетить музей', 1),
  ('iglesia', 'церковь', 'noun', 'Iglesia antigua', 'Старая церковь', 2),
  ('castillo', 'замок', 'noun', 'Castillo medieval', 'Средневековый замок', 2),
  ('monumento', 'памятник', 'noun', 'Monumento histórico', 'Исторический памятник', 2),
  ('parque', 'парк', 'noun', 'Pasear por el parque', 'Гулять по парку', 1),
  ('jardín', 'сад', 'noun', 'Jardín botánico', 'Ботанический сад', 2),
  ('río', 'река', 'noun', 'Río grande', 'Большая река', 1),
  ('lago', 'озеро', 'noun', 'Lago tranquilo', 'Спокойное озеро', 2),
  ('mar', 'море', 'noun', 'Vista al mar', 'Вид на море', 1),
  ('océano', 'океан', 'noun', 'Océano Atlántico', 'Атлантический океан', 2),
  ('isla', 'остров', 'noun', 'Isla tropical', 'Тропический остров', 2),
  ('norte', 'север', 'noun', 'Ir al norte', 'Ехать на север', 1),
  ('sur', 'юг', 'noun', 'Viajar al sur', 'Путешествовать на юг', 1),
  ('este', 'восток', 'noun', 'Hacia el este', 'На восток', 1),
  ('oeste', 'запад', 'noun', 'Puesta de sol al oeste', 'Закат на западе', 1),
  ('derecha', 'направо', 'noun', 'Girar a la derecha', 'Повернуть направо', 1),
  ('izquierda', 'налево', 'noun', 'Girar a la izquierda', 'Повернуть налево', 1),
  ('recto', 'прямо', 'adverb', 'Seguir recto', 'Идти прямо', 1),
  ('cerca', 'близко', 'adverb', 'Está muy cerca', 'Это очень близко', 1),
  ('lejos', 'далеко', 'adverb', 'Está lejos', 'Это далеко', 1),
  ('aquí', 'здесь', 'adverb', 'Estoy aquí', 'Я здесь', 1),
  ('allí', 'там', 'adverb', 'Está allí', 'Это там', 1),
  ('entrada', 'вход', 'noun', 'Entrada principal', 'Главный вход', 1),
  ('salida', 'выход', 'noun', 'Salida de emergencia', 'Аварийный выход', 1),
  ('información', 'информация', 'noun', 'Oficina de información', 'Информационное бюро', 2),
  ('precio', 'цена', 'noun', '¿Cuál es el precio?', 'Какая цена?', 1),
  ('dinero', 'деньги', 'noun', 'Cambiar dinero', 'Обменять деньги', 1),
  ('tarjeta', 'карта', 'noun', 'Pagar con tarjeta', 'Платить картой', 1),
  ('efectivo', 'наличные', 'noun', 'Pagar en efectivo', 'Платить наличными', 2),
  ('banco', 'банк', 'noun', 'Ir al banco', 'Идти в банк', 1),
  ('cajero', 'банкомат', 'noun', 'Sacar dinero del cajero', 'Снять деньги в банкомате', 2),
  ('cambio', 'сдача', 'noun', 'Quedarse con el cambio', 'Оставить сдачу', 2),
  ('tienda', 'магазин', 'noun', 'Ir de tiendas', 'Ходить по магазинам', 1),
  ('mercado', 'рынок', 'noun', 'Mercado local', 'Местный рынок', 1),
  ('supermercado', 'супермаркет', 'noun', 'Comprar en el supermercado', 'Покупать в супермаркете', 1),
  ('farmacia', 'аптека', 'noun', 'Buscar una farmacia', 'Искать аптеку', 1),
  ('hospital', 'больница', 'noun', 'Ir al hospital', 'Ехать в больницу', 1),
  ('médico', 'врач', 'noun', 'Visitar al médico', 'Посетить врача', 1),
  ('policía', 'полиция', 'noun', 'Llamar a la policía', 'Вызвать полицию', 1),
  ('ayuda', 'помощь', 'noun', 'Necesito ayuda', 'Мне нужна помощь', 1),
  ('peligro', 'опасность', 'noun', 'Señal de peligro', 'Знак опасности', 2),
  ('seguro', 'безопасный', 'adjective', 'Lugar seguro', 'Безопасное место', 1),
  ('perdido', 'потерянный', 'adjective', 'Estoy perdido', 'Я потерялся', 1),
  ('abierto', 'открытый', 'adjective', 'Está abierto', 'Открыто', 1),
  ('cerrado', 'закрытый', 'adjective', 'Está cerrado', 'Закрыто', 1),
  ('horario', 'расписание', 'noun', 'Horario de trenes', 'Расписание поездов', 2),
  ('hora', 'час', 'noun', '¿Qué hora es?', 'Который час?', 1),
  ('minuto', 'минута', 'noun', 'Cinco minutos', 'Пять минут', 1),
  ('día', 'день', 'noun', 'Buen día', 'Добрый день', 1),
  ('noche', 'ночь', 'noun', 'Buenas noches', 'Спокойной ночи', 1),
  ('mañana', 'утро', 'noun', 'Por la mañana', 'Утром', 1),
  ('tarde', 'вечер', 'noun', 'Por la tarde', 'Вечером', 1),
  ('hoy', 'сегодня', 'adverb', 'Hoy hace sol', 'Сегодня солнечно', 1),
  ('ayer', 'вчера', 'adverb', 'Ayer llovió', 'Вчера был дождь', 1),
  ('mañana', 'завтра', 'adverb', 'Hasta mañana', 'До завтра', 1),
  ('viajar', 'путешествовать', 'verb', 'Me gusta viajar', 'Мне нравится путешествовать', 1),
  ('llegar', 'прибывать', 'verb', 'Llegar a tiempo', 'Прибыть вовремя', 2),
  ('salir', 'уезжать', 'verb', 'Salir de viaje', 'Уезжать в путешествие', 1),
  ('buscar', 'искать', 'verb', 'Buscar el hotel', 'Искать отель', 1),
  ('encontrar', 'находить', 'verb', 'Encontrar el camino', 'Найти дорогу', 2),
  ('preguntar', 'спрашивать', 'verb', 'Preguntar la dirección', 'Спрашивать направление', 2),
  ('esperar', 'ждать', 'verb', 'Esperar el autobús', 'Ждать автобус', 1),
  ('caminar', 'идти пешком', 'verb', 'Caminar por la ciudad', 'Гулять по городу', 1),
  ('correr', 'бежать', 'verb', 'Correr para el tren', 'Бежать на поезд', 1),
  ('parar', 'останавливаться', 'verb', 'Parar el taxi', 'Остановить такси', 1),
  ('subir', 'подниматься', 'verb', 'Subir al avión', 'Садиться в самолёт', 2),
  ('bajar', 'спускаться', 'verb', 'Bajar del tren', 'Выходить из поезда', 2)
) AS t(spanish, russian, part_of_speech, example_es, example_ru, difficulty);

-- Deck 3: Daily Life (100 words)
INSERT INTO cards (deck_id, spanish, russian, part_of_speech, example_es, example_ru, difficulty) 
SELECT 
  (SELECT id FROM decks WHERE topic = 'daily'),
  spanish, russian, part_of_speech, example_es, example_ru, difficulty
FROM (VALUES
  ('casa', 'дом', 'noun', 'Mi casa es grande', 'Мой дом большой', 1),
  ('apartamento', 'квартира', 'noun', 'Vivo en un apartamento', 'Я живу в квартире', 1),
  ('puerta', 'дверь', 'noun', 'Abrir la puerta', 'Открыть дверь', 1),
  ('ventana', 'окно', 'noun', 'Cerrar la ventana', 'Закрыть окно', 1),
  ('pared', 'стена', 'noun', 'Pintar la pared', 'Красить стену', 2),
  ('techo', 'потолок', 'noun', 'Techo alto', 'Высокий потолок', 2),
  ('suelo', 'пол', 'noun', 'Limpiar el suelo', 'Мыть пол', 2),
  ('escalera', 'лестница', 'noun', 'Subir las escaleras', 'Подниматься по лестнице', 2),
  ('ascensor', 'лифт', 'noun', 'Tomar el ascensor', 'Взять лифт', 2),
  ('sala', 'гостиная', 'noun', 'Sala de estar', 'Гостиная', 1),
  ('dormitorio', 'спальня', 'noun', 'Mi dormitorio', 'Моя спальня', 1),
  ('baño', 'ванная', 'noun', 'Ir al baño', 'Идти в ванную', 1),
  ('cocina', 'кухня', 'noun', 'Cocinar en la cocina', 'Готовить на кухне', 1),
  ('comedor', 'столовая', 'noun', 'Comer en el comedor', 'Есть в столовой', 2),
  ('jardín', 'сад', 'noun', 'Trabajar en el jardín', 'Работать в саду', 1),
  ('garaje', 'гараж', 'noun', 'Coche en el garaje', 'Машина в гараже', 2),
  ('cama', 'кровать', 'noun', 'Hacer la cama', 'Застилать кровать', 1),
  ('sofá', 'диван', 'noun', 'Sentarse en el sofá', 'Сидеть на диване', 1),
  ('sillón', 'кресло', 'noun', 'Sillón cómodo', 'Удобное кресло', 2),
  ('mesa', 'стол', 'noun', 'Mesa de comedor', 'Обеденный стол', 1),
  ('silla', 'стул', 'noun', 'Cuatro sillas', 'Четыре стула', 1),
  ('armario', 'шкаф', 'noun', 'Ropa en el armario', 'Одежда в шкафу', 2),
  ('estantería', 'полка', 'noun', 'Libros en la estantería', 'Книги на полке', 2),
  ('lámpara', 'лампа', 'noun', 'Encender la lámpara', 'Включить лампу', 1),
  ('luz', 'свет', 'noun', 'Apagar la luz', 'Выключить свет', 1),
  ('televisión', 'телевизор', 'noun', 'Ver la televisión', 'Смотреть телевизор', 1),
  ('radio', 'радио', 'noun', 'Escuchar la radio', 'Слушать радио', 1),
  ('ordenador', 'компьютер', 'noun', 'Trabajar en el ordenador', 'Работать на компьютере', 1),
  ('teléfono', 'телефон', 'noun', 'Llamar por teléfono', 'Звонить по телефону', 1),
  ('móvil', 'мобильный', 'noun', 'Teléfono móvil', 'Мобильный телефон', 1),
  ('reloj', 'часы', 'noun', 'Mirar el reloj', 'Смотреть на часы', 1),
  ('libro', 'книга', 'noun', 'Leer un libro', 'Читать книгу', 1),
  ('revista', 'журнал', 'noun', 'Revista de moda', 'Модный журнал', 2),
  ('periódico', 'газета', 'noun', 'Leer el periódico', 'Читать газету', 2),
  ('papel', 'бумага', 'noun', 'Hoja de papel', 'Лист бумаги', 1),
  ('bolígrafo', 'ручка', 'noun', 'Escribir con bolígrafo', 'Писать ручкой', 1),
  ('lápiz', 'карандаш', 'noun', 'Dibujar con lápiz', 'Рисовать карандашом', 1),
  ('cuaderno', 'тетрадь', 'noun', 'Cuaderno de notas', 'Тетрадь для записей', 1),
  ('carta', 'письмо', 'noun', 'Escribir una carta', 'Написать письмо', 2),
  ('sobre', 'конверт', 'noun', 'Meter en el sobre', 'Положить в конверт', 2),
  ('sello', 'марка', 'noun', 'Pegar un sello', 'Наклеить марку', 2),
  ('correo', 'почта', 'noun', 'Ir al correo', 'Идти на почту', 1),
  ('paquete', 'посылка', 'noun', 'Enviar un paquete', 'Отправить посылку', 2),
  ('ropa', 'одежда', 'noun', 'Comprar ropa', 'Покупать одежду', 1),
  ('camisa', 'рубашка', 'noun', 'Camisa blanca', 'Белая рубашка', 1),
  ('camiseta', 'футболка', 'noun', 'Camiseta de algodón', 'Хлопковая футболка', 1),
  ('pantalón', 'брюки', 'noun', 'Pantalones vaqueros', 'Джинсы', 1),
  ('falda', 'юбка', 'noun', 'Falda larga', 'Длинная юбка', 1),
  ('vestido', 'платье', 'noun', 'Vestido elegante', 'Элегантное платье', 1),
  ('chaqueta', 'куртка', 'noun', 'Chaqueta de cuero', 'Кожаная куртка', 1),
  ('abrigo', 'пальто', 'noun', 'Abrigo de invierno', 'Зимнее пальто', 2),
  ('zapato', 'туфли', 'noun', 'Zapatos nuevos', 'Новые туфли', 1),
  ('zapatilla', 'кроссовки', 'noun', 'Zapatillas deportivas', 'Спортивные кроссовки', 1),
  ('calcetín', 'носок', 'noun', 'Par de calcetines', 'Пара носков', 2),
  ('sombrero', 'шляпа', 'noun', 'Sombrero de sol', 'Шляпа от солнца', 2),
  ('gorra', 'кепка', 'noun', 'Gorra de béisbol', 'Бейсболка', 2),
  ('gafas', 'очки', 'noun', 'Gafas de sol', 'Солнечные очки', 1),
  ('reloj', 'часы (наручные)', 'noun', 'Reloj de pulsera', 'Наручные часы', 1),
  ('bolso', 'сумка', 'noun', 'Bolso de mano', 'Ручная сумка', 1),
  ('cartera', 'кошелёк', 'noun', 'Dinero en la cartera', 'Деньги в кошельке', 2),
  ('paraguas', 'зонт', 'noun', 'Llevar paraguas', 'Нести зонт', 2),
  ('jabón', 'мыло', 'noun', 'Lavarse con jabón', 'Мыться мылом', 1),
  ('champú', 'шампунь', 'noun', 'Champú para el pelo', 'Шампунь для волос', 2),
  ('toalla', 'полотенце', 'noun', 'Secarse con toalla', 'Вытираться полотенцем', 1),
  ('cepillo', 'щётка', 'noun', 'Cepillo de dientes', 'Зубная щётка', 1),
  ('pasta', 'паста', 'noun', 'Pasta de dientes', 'Зубная паста', 1),
  ('peine', 'расчёска', 'noun', 'Peinarse el pelo', 'Расчёсывать волосы', 2),
  ('espejo', 'зеркало', 'noun', 'Mirarse al espejo', 'Смотреться в зеркало', 1),
  ('ducha', 'душ', 'noun', 'Tomar una ducha', 'Принимать душ', 1),
  ('bañera', 'ванна', 'noun', 'Llenar la bañera', 'Наполнять ванну', 2),
  ('agua', 'вода', 'noun', 'Agua caliente', 'Горячая вода', 1),
  ('grifo', 'кран', 'noun', 'Abrir el grifo', 'Открыть кран', 2),
  ('basura', 'мусор', 'noun', 'Tirar la basura', 'Выбрасывать мусор', 1),
  ('cubo', 'ведро', 'noun', 'Cubo de basura', 'Мусорное ведро', 2),
  ('escoba', 'метла', 'noun', 'Barrer con escoba', 'Подметать метлой', 2),
  ('fregona', 'швабра', 'noun', 'Fregar el suelo', 'Мыть пол', 2),
  ('limpio', 'чистый', 'adjective', 'Casa limpia', 'Чистый дом', 1),
  ('sucio', 'грязный', 'adjective', 'Ropa sucia', 'Грязная одежда', 1),
  ('nuevo', 'новый', 'adjective', 'Coche nuevo', 'Новая машина', 1),
  ('viejo', 'старый', 'adjective', 'Libro viejo', 'Старая книга', 1),
  ('grande', 'большой', 'adjective', 'Casa grande', 'Большой дом', 1),
  ('pequeño', 'маленький', 'adjective', 'Perro pequeño', 'Маленькая собака', 1),
  ('bonito', 'красивый', 'adjective', 'Vestido bonito', 'Красивое платье', 1),
  ('feo', 'некрасивый', 'adjective', 'Edificio feo', 'Некрасивое здание', 1),
  ('cómodo', 'удобный', 'adjective', 'Sofá cómodo', 'Удобный диван', 2),
  ('incómodo', 'неудобный', 'adjective', 'Silla incómoda', 'Неудобный стул', 2),
  ('vivir', 'жить', 'verb', 'Vivir en Madrid', 'Жить в Мадриде', 1),
  ('dormir', 'спать', 'verb', 'Dormir bien', 'Хорошо спать', 1),
  ('despertar', 'просыпаться', 'verb', 'Despertarse temprano', 'Просыпаться рано', 2),
  ('levantarse', 'вставать', 'verb', 'Levantarse de la cama', 'Вставать с кровати', 2),
  ('lavar', 'мыть', 'verb', 'Lavar los platos', 'Мыть посуду', 1),
  ('limpiar', 'убирать', 'verb', 'Limpiar la casa', 'Убирать дом', 1),
  ('ordenar', 'приводить в порядок', 'verb', 'Ordenar la habitación', 'Приводить комнату в порядок', 2),
  ('planchar', 'гладить', 'verb', 'Planchar la ropa', 'Гладить одежду', 2),
  ('coser', 'шить', 'verb', 'Coser un botón', 'Пришивать пуговицу', 2),
  ('abrir', 'открывать', 'verb', 'Abrir la ventana', 'Открывать окно', 1),
  ('cerrar', 'закрывать', 'verb', 'Cerrar la puerta', 'Закрывать дверь', 1),
  ('encender', 'включать', 'verb', 'Encender la luz', 'Включать свет', 2),
  ('apagar', 'выключать', 'verb', 'Apagar la televisión', 'Выключать телевизор', 2)
) AS t(spanish, russian, part_of_speech, example_es, example_ru, difficulty);

-- Deck 4: Common Verbs (100 words)
INSERT INTO cards (deck_id, spanish, russian, part_of_speech, example_es, example_ru, difficulty) 
SELECT 
  (SELECT id FROM decks WHERE topic = 'verbs'),
  spanish, russian, part_of_speech, example_es, example_ru, difficulty
FROM (VALUES
  ('ser', 'быть (постоянное)', 'verb', 'Soy estudiante', 'Я студент', 1),
  ('estar', 'быть (временное)', 'verb', 'Estoy cansado', 'Я устал', 1),
  ('tener', 'иметь', 'verb', 'Tengo un coche', 'У меня есть машина', 1),
  ('hacer', 'делать', 'verb', 'Hacer la tarea', 'Делать домашнее задание', 1),
  ('ir', 'идти', 'verb', 'Voy al trabajo', 'Я иду на работу', 1),
  ('venir', 'приходить', 'verb', 'Vengo mañana', 'Я приду завтра', 2),
  ('poder', 'мочь', 'verb', 'Puedo ayudarte', 'Я могу помочь тебе', 1),
  ('querer', 'хотеть', 'verb', 'Quiero café', 'Я хочу кофе', 1),
  ('deber', 'быть должным', 'verb', 'Debo estudiar', 'Я должен учиться', 2),
  ('saber', 'знать', 'verb', 'Sé español', 'Я знаю испанский', 1),
  ('conocer', 'знать (быть знакомым)', 'verb', 'Conozco Madrid', 'Я знаю Мадрид', 2),
  ('ver', 'видеть', 'verb', 'Veo la televisión', 'Я смотрю телевизор', 1),
  ('mirar', 'смотреть', 'verb', 'Mirar por la ventana', 'Смотреть в окно', 1),
  ('oír', 'слышать', 'verb', 'Oigo música', 'Я слышу музыку', 2),
  ('escuchar', 'слушать', 'verb', 'Escuchar la radio', 'Слушать радио', 1),
  ('hablar', 'говорить', 'verb', 'Hablar español', 'Говорить по-испански', 1),
  ('decir', 'сказать', 'verb', 'Decir la verdad', 'Сказать правду', 1),
  ('preguntar', 'спрашивать', 'verb', 'Preguntar algo', 'Спросить что-то', 1),
  ('responder', 'отвечать', 'verb', 'Responder rápido', 'Отвечать быстро', 2),
  ('contestar', 'отвечать', 'verb', 'Contestar el teléfono', 'Отвечать на телефон', 2),
  ('llamar', 'звонить', 'verb', 'Llamar por teléfono', 'Звонить по телефону', 1),
  ('gritar', 'кричать', 'verb', 'No grites', 'Не кричи', 2),
  ('llorar', 'плакать', 'verb', 'El bebé llora', 'Ребёнок плачет', 2),
  ('reír', 'смеяться', 'verb', 'Reír mucho', 'Много смеяться', 2),
  ('sonreír', 'улыбаться', 'verb', 'Sonreír siempre', 'Всегда улыбаться', 2),
  ('pensar', 'думать', 'verb', 'Pensar en ti', 'Думать о тебе', 1),
  ('creer', 'верить', 'verb', 'Creo que sí', 'Я думаю, что да', 2),
  ('entender', 'понимать', 'verb', 'No entiendo', 'Я не понимаю', 1),
  ('comprender', 'понимать', 'verb', 'Comprender el problema', 'Понимать проблему', 2),
  ('aprender', 'учить', 'verb', 'Aprender español', 'Учить испанский', 1),
  ('enseñar', 'учить (преподавать)', 'verb', 'Enseñar matemáticas', 'Преподавать математику', 2),
  ('estudiar', 'учиться', 'verb', 'Estudiar mucho', 'Много учиться', 1),
  ('leer', 'читать', 'verb', 'Leer un libro', 'Читать книгу', 1),
  ('escribir', 'писать', 'verb', 'Escribir una carta', 'Писать письмо', 1),
  ('dibujar', 'рисовать', 'verb', 'Dibujar un cuadro', 'Рисовать картину', 1),
  ('pintar', 'красить', 'verb', 'Pintar la pared', 'Красить стену', 1),
  ('cantar', 'петь', 'verb', 'Cantar una canción', 'Петь песню', 1),
  ('bailar', 'танцевать', 'verb', 'Bailar salsa', 'Танцевать сальсу', 1),
  ('tocar', 'играть (на инструменте)', 'verb', 'Tocar la guitarra', 'Играть на гитаре', 1),
  ('jugar', 'играть', 'verb', 'Jugar al fútbol', 'Играть в футбол', 1),
  ('ganar', 'выигрывать', 'verb', 'Ganar el partido', 'Выиграть матч', 2),
  ('perder', 'проигрывать', 'verb', 'Perder el juego', 'Проиграть игру', 2),
  ('trabajar', 'работать', 'verb', 'Trabajar duro', 'Работать усердно', 1),
  ('descansar', 'отдыхать', 'verb', 'Descansar un poco', 'Немного отдохнуть', 1),
  ('dormir', 'спать', 'verb', 'Dormir ocho horas', 'Спать восемь часов', 1),
  ('soñar', 'мечтать', 'verb', 'Soñar con viajar', 'Мечтать о путешествии', 2),
  ('vivir', 'жить', 'verb', 'Vivir en España', 'Жить в Испании', 1),
  ('morir', 'умирать', 'verb', 'Morir de viejo', 'Умереть от старости', 3),
  ('nacer', 'рождаться', 'verb', 'Nacer en Madrid', 'Родиться в Мадриде', 2),
  ('crecer', 'расти', 'verb', 'Crecer rápido', 'Быстро расти', 2),
  ('amar', 'любить', 'verb', 'Amar a alguien', 'Любить кого-то', 2),
  ('odiar', 'ненавидеть', 'verb', 'Odiar el frío', 'Ненавидеть холод', 2),
  ('gustar', 'нравиться', 'verb', 'Me gusta el café', 'Мне нравится кофе', 1),
  ('preferir', 'предпочитать', 'verb', 'Prefiero té', 'Я предпочитаю чай', 2),
  ('necesitar', 'нуждаться', 'verb', 'Necesito ayuda', 'Мне нужна помощь', 1),
  ('desear', 'желать', 'verb', 'Desear buena suerte', 'Желать удачи', 2),
  ('esperar', 'ждать', 'verb', 'Esperar el autobús', 'Ждать автобус', 1),
  ('buscar', 'искать', 'verb', 'Buscar las llaves', 'Искать ключи', 1),
  ('encontrar', 'находить', 'verb', 'Encontrar la solución', 'Найти решение', 2),
  ('perder', 'терять', 'verb', 'Perder el tiempo', 'Терять время', 2),
  ('dar', 'давать', 'verb', 'Dar un regalo', 'Дать подарок', 1),
  ('recibir', 'получать', 'verb', 'Recibir una carta', 'Получить письмо', 2),
  ('tomar', 'брать', 'verb', 'Tomar el autobús', 'Взять автобус', 1),
  ('coger', 'брать', 'verb', 'Coger el tren', 'Взять поезд', 2),
  ('dejar', 'оставлять', 'verb', 'Dejar las llaves', 'Оставить ключи', 2),
  ('poner', 'класть', 'verb', 'Poner la mesa', 'Накрывать на стол', 2),
  ('llevar', 'нести', 'verb', 'Llevar una maleta', 'Нести чемодан', 2),
  ('traer', 'приносить', 'verb', 'Traer el libro', 'Принести книгу', 2),
  ('enviar', 'отправлять', 'verb', 'Enviar un email', 'Отправить email', 2),
  ('mandar', 'посылать', 'verb', 'Mandar un paquete', 'Послать посылку', 2),
  ('comprar', 'покупать', 'verb', 'Comprar comida', 'Покупать еду', 1),
  ('vender', 'продавать', 'verb', 'Vender el coche', 'Продавать машину', 2),
  ('pagar', 'платить', 'verb', 'Pagar la cuenta', 'Платить счёт', 1),
  ('costar', 'стоить', 'verb', 'Cuesta mucho', 'Стоит дорого', 2),
  ('gastar', 'тратить', 'verb', 'Gastar dinero', 'Тратить деньги', 2),
  ('ahorrar', 'экономить', 'verb', 'Ahorrar dinero', 'Экономить деньги', 2),
  ('usar', 'использовать', 'verb', 'Usar el ordenador', 'Использовать компьютер', 1),
  ('utilizar', 'использовать', 'verb', 'Utilizar una herramienta', 'Использовать инструмент', 2),
  ('ayudar', 'помогать', 'verb', 'Ayudar a alguien', 'Помогать кому-то', 1),
  ('cuidar', 'заботиться', 'verb', 'Cuidar a los niños', 'Заботиться о детях', 2),
  ('proteger', 'защищать', 'verb', 'Proteger la naturaleza', 'Защищать природу', 2),
  ('salvar', 'спасать', 'verb', 'Salvar una vida', 'Спасти жизнь', 2),
  ('matar', 'убивать', 'verb', 'Matar un insecto', 'Убить насекомое', 3),
  ('romper', 'ломать', 'verb', 'Romper un vaso', 'Разбить стакан', 2),
  ('arreglar', 'чинить', 'verb', 'Arreglar el coche', 'Чинить машину', 2),
  ('construir', 'строить', 'verb', 'Construir una casa', 'Строить дом', 2),
  ('destruir', 'разрушать', 'verb', 'Destruir el edificio', 'Разрушать здание', 3),
  ('crear', 'создавать', 'verb', 'Crear arte', 'Создавать искусство', 2),
  ('cambiar', 'менять', 'verb', 'Cambiar de opinión', 'Менять мнение', 2),
  ('mejorar', 'улучшать', 'verb', 'Mejorar la situación', 'Улучшать ситуацию', 2),
  ('empeorar', 'ухудшать', 'verb', 'Empeorar el problema', 'Ухудшать проблему', 3),
  ('comenzar', 'начинать', 'verb', 'Comenzar el trabajo', 'Начинать работу', 2),
  ('empezar', 'начинать', 'verb', 'Empezar la clase', 'Начинать урок', 2),
  ('terminar', 'заканчивать', 'verb', 'Terminar el proyecto', 'Заканчивать проект', 2),
  ('acabar', 'заканчивать', 'verb', 'Acabar la tarea', 'Заканчивать задание', 2),
  ('continuar', 'продолжать', 'verb', 'Continuar trabajando', 'Продолжать работать', 2),
  ('seguir', 'следовать', 'verb', 'Seguir adelante', 'Идти вперёд', 2),
  ('parar', 'останавливать', 'verb', 'Parar el coche', 'Остановить машину', 1),
  ('detener', 'останавливать', 'verb', 'Detener el tiempo', 'Остановить время', 3)
) AS t(spanish, russian, part_of_speech, example_es, example_ru, difficulty);

-- Deck 5: Common Adjectives (100 words)
INSERT INTO cards (deck_id, spanish, russian, part_of_speech, example_es, example_ru, difficulty) 
SELECT 
  (SELECT id FROM decks WHERE topic = 'adjectives'),
  spanish, russian, part_of_speech, example_es, example_ru, difficulty
FROM (VALUES
  ('bueno', 'хороший', 'adjective', 'Un buen día', 'Хороший день', 1),
  ('malo', 'плохой', 'adjective', 'Mal tiempo', 'Плохая погода', 1),
  ('grande', 'большой', 'adjective', 'Casa grande', 'Большой дом', 1),
  ('pequeño', 'маленький', 'adjective', 'Niño pequeño', 'Маленький ребёнок', 1),
  ('alto', 'высокий', 'adjective', 'Hombre alto', 'Высокий мужчина', 1),
  ('bajo', 'низкий', 'adjective', 'Mesa baja', 'Низкий стол', 1),
  ('largo', 'длинный', 'adjective', 'Pelo largo', 'Длинные волосы', 1),
  ('corto', 'короткий', 'adjective', 'Falda corta', 'Короткая юбка', 1),
  ('ancho', 'широкий', 'adjective', 'Calle ancha', 'Широкая улица', 2),
  ('estrecho', 'узкий', 'adjective', 'Pasillo estrecho', 'Узкий коридор', 2),
  ('gordo', 'толстый', 'adjective', 'Gato gordo', 'Толстый кот', 1),
  ('delgado', 'худой', 'adjective', 'Persona delgada', 'Худой человек', 2),
  ('fuerte', 'сильный', 'adjective', 'Hombre fuerte', 'Сильный мужчина', 1),
  ('débil', 'слабый', 'adjective', 'Señal débil', 'Слабый сигнал', 2),
  ('rápido', 'быстрый', 'adjective', 'Coche rápido', 'Быстрая машина', 1),
  ('lento', 'медленный', 'adjective', 'Tren lento', 'Медленный поезд', 1),
  ('fácil', 'лёгкий', 'adjective', 'Ejercicio fácil', 'Лёгкое упражнение', 1),
  ('difícil', 'трудный', 'adjective', 'Problema difícil', 'Трудная проблема', 1),
  ('nuevo', 'новый', 'adjective', 'Libro nuevo', 'Новая книга', 1),
  ('viejo', 'старый', 'adjective', 'Coche viejo', 'Старая машина', 1),
  ('joven', 'молодой', 'adjective', 'Chica joven', 'Молодая девушка', 1),
  ('antiguo', 'древний', 'adjective', 'Ciudad antigua', 'Древний город', 2),
  ('moderno', 'современный', 'adjective', 'Arte moderno', 'Современное искусство', 2),
  ('bonito', 'красивый', 'adjective', 'Vestido bonito', 'Красивое платье', 1),
  ('feo', 'некрасивый', 'adjective', 'Edificio feo', 'Некрасивое здание', 1),
  ('hermoso', 'прекрасный', 'adjective', 'Paisaje hermoso', 'Прекрасный пейзаж', 2),
  ('guapo', 'красивый (о человеке)', 'adjective', 'Hombre guapo', 'Красивый мужчина', 1),
  ('lindo', 'милый', 'adjective', 'Bebé lindo', 'Милый малыш', 1),
  ('rico', 'богатый', 'adjective', 'Familia rica', 'Богатая семья', 1),
  ('pobre', 'бедный', 'adjective', 'País pobre', 'Бедная страна', 1),
  ('caro', 'дорогой', 'adjective', 'Reloj caro', 'Дорогие часы', 1),
  ('barato', 'дешёвый', 'adjective', 'Comida barata', 'Дешёвая еда', 1),
  ('limpio', 'чистый', 'adjective', 'Casa limpia', 'Чистый дом', 1),
  ('sucio', 'грязный', 'adjective', 'Ropa sucia', 'Грязная одежда', 1),
  ('claro', 'светлый', 'adjective', 'Color claro', 'Светлый цвет', 1),
  ('oscuro', 'тёмный', 'adjective', 'Noche oscura', 'Тёмная ночь', 1),
  ('blanco', 'белый', 'adjective', 'Camisa blanca', 'Белая рубашка', 1),
  ('negro', 'чёрный', 'adjective', 'Gato negro', 'Чёрный кот', 1),
  ('rojo', 'красный', 'adjective', 'Rosa roja', 'Красная роза', 1),
  ('azul', 'синий', 'adjective', 'Cielo azul', 'Синее небо', 1),
  ('verde', 'зелёный', 'adjective', 'Hierba verde', 'Зелёная трава', 1),
  ('amarillo', 'жёлтый', 'adjective', 'Sol amarillo', 'Жёлтое солнце', 1),
  ('gris', 'серый', 'adjective', 'Nube gris', 'Серое облако', 1),
  ('marrón', 'коричневый', 'adjective', 'Zapatos marrones', 'Коричневые туфли', 2),
  ('rosa', 'розовый', 'adjective', 'Flor rosa', 'Розовый цветок', 1),
  ('naranja', 'оранжевый', 'adjective', 'Fruta naranja', 'Оранжевый фрукт', 1),
  ('morado', 'фиолетовый', 'adjective', 'Vestido morado', 'Фиолетовое платье', 2),
  ('caliente', 'горячий', 'adjective', 'Café caliente', 'Горячий кофе', 1),
  ('frío', 'холодный', 'adjective', 'Agua fría', 'Холодная вода', 1),
  ('tibio', 'тёплый', 'adjective', 'Leche tibia', 'Тёплое молоко', 2),
  ('dulce', 'сладкий', 'adjective', 'Pastel dulce', 'Сладкий торт', 1),
  ('salado', 'солёный', 'adjective', 'Sopa salada', 'Солёный суп', 1),
  ('amargo', 'горький', 'adjective', 'Café amargo', 'Горький кофе', 2),
  ('ácido', 'кислый', 'adjective', 'Limón ácido', 'Кислый лимон', 2),
  ('picante', 'острый', 'adjective', 'Salsa picante', 'Острый соус', 2),
  ('suave', 'мягкий', 'adjective', 'Almohada suave', 'Мягкая подушка', 2),
  ('duro', 'твёрдый', 'adjective', 'Pan duro', 'Твёрдый хлеб', 1),
  ('blando', 'мягкий', 'adjective', 'Carne blanda', 'Мягкое мясо', 2),
  ('seco', 'сухой', 'adjective', 'Clima seco', 'Сухой климат', 2),
  ('mojado', 'мокрый', 'adjective', 'Ropa mojada', 'Мокрая одежда', 1),
  ('húmedo', 'влажный', 'adjective', 'Aire húmedo', 'Влажный воздух', 2),
  ('lleno', 'полный', 'adjective', 'Vaso lleno', 'Полный стакан', 1),
  ('vacío', 'пустой', 'adjective', 'Botella vacía', 'Пустая бутылка', 1),
  ('abierto', 'открытый', 'adjective', 'Puerta abierta', 'Открытая дверь', 1),
  ('cerrado', 'закрытый', 'adjective', 'Ventana cerrada', 'Закрытое окно', 1),
  ('feliz', 'счастливый', 'adjective', 'Persona feliz', 'Счастливый человек', 1),
  ('triste', 'грустный', 'adjective', 'Niño triste', 'Грустный ребёнок', 1),
  ('alegre', 'весёлый', 'adjective', 'Fiesta alegre', 'Весёлая вечеринка', 2),
  ('contento', 'довольный', 'adjective', 'Cliente contento', 'Довольный клиент', 2),
  ('enfadado', 'сердитый', 'adjective', 'Padre enfadado', 'Сердитый отец', 2),
  ('enojado', 'злой', 'adjective', 'Jefe enojado', 'Злой начальник', 2),
  ('cansado', 'уставший', 'adjective', 'Trabajador cansado', 'Уставший работник', 1),
  ('aburrido', 'скучный', 'adjective', 'Película aburrida', 'Скучный фильм', 1),
  ('interesante', 'интересный', 'adjective', 'Libro interesante', 'Интересная книга', 1),
  ('divertido', 'весёлый', 'adjective', 'Juego divertido', 'Весёлая игра', 2),
  ('emocionante', 'захватывающий', 'adjective', 'Partido emocionante', 'Захватывающий матч', 2),
  ('tranquilo', 'спокойный', 'adjective', 'Lugar tranquilo', 'Спокойное место', 2),
  ('ruidoso', 'шумный', 'adjective', 'Bar ruidoso', 'Шумный бар', 2),
  ('silencioso', 'тихий', 'adjective', 'Biblioteca silenciosa', 'Тихая библиотека', 2),
  ('importante', 'важный', 'adjective', 'Reunión importante', 'Важная встреча', 1),
  ('necesario', 'необходимый', 'adjective', 'Documento necesario', 'Необходимый документ', 2),
  ('útil', 'полезный', 'adjective', 'Herramienta útil', 'Полезный инструмент', 2),
  ('inútil', 'бесполезный', 'adjective', 'Objeto inútil', 'Бесполезный предмет', 2),
  ('posible', 'возможный', 'adjective', 'Es posible', 'Это возможно', 2),
  ('imposible', 'невозможный', 'adjective', 'Tarea imposible', 'Невозможная задача', 2),
  ('probable', 'вероятный', 'adjective', 'Resultado probable', 'Вероятный результат', 2),
  ('seguro', 'уверенный', 'adjective', 'Estoy seguro', 'Я уверен', 1),
  ('peligroso', 'опасный', 'adjective', 'Animal peligroso', 'Опасное животное', 2),
  ('seguro', 'безопасный', 'adjective', 'Lugar seguro', 'Безопасное место', 1),
  ('correcto', 'правильный', 'adjective', 'Respuesta correcta', 'Правильный ответ', 2),
  ('incorrecto', 'неправильный', 'adjective', 'Dato incorrecto', 'Неправильные данные', 2),
  ('verdadero', 'истинный', 'adjective', 'Historia verdadera', 'Правдивая история', 2),
  ('falso', 'ложный', 'adjective', 'Noticia falsa', 'Ложная новость', 2),
  ('real', 'реальный', 'adjective', 'Mundo real', 'Реальный мир', 2),
  ('perfecto', 'идеальный', 'adjective', 'Día perfecto', 'Идеальный день', 2),
  ('normal', 'нормальный', 'adjective', 'Situación normal', 'Нормальная ситуация', 1),
  ('extraño', 'странный', 'adjective', 'Sonido extraño', 'Странный звук', 2),
  ('raro', 'редкий', 'adjective', 'Animal raro', 'Редкое животное', 2),
  ('común', 'обычный', 'adjective', 'Problema común', 'Обычная проблема', 2),
  ('especial', 'особенный', 'adjective', 'Día especial', 'Особенный день', 2)
) AS t(spanish, russian, part_of_speech, example_es, example_ru, difficulty);
